languageCode = "en-us"
langs.Language = "en-us"
title = "Grostlpedia"
theme = "grostl-review-theme"
author = "MiraSki"
description = "The Wikipedia for Tiroler Gröstl"
image = "/images/pistezicht.png"

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
  [languages.nl]
    languageName = "Dutch"